# Stage 1
FROM node:14.17.0 as build
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
ARG REACT_APP_NAME
ENV REACT_APP_NAME=$REACT_APP_NAME
RUN npm run build

# Stage 2
FROM nginx
COPY --from=build /app/build /usr/share/nginx/html
